### ISSUE TITLE
RN 0.42 not working

### ISSUE THREAD

**Issue by kasterlod** [react-native-community/react-native-drawer-layout#11] opened 2017-03-08 07:02 UTC
DrawerLayout (tested on android only) --> navigator menu not hiding but slide to right and stop in the middle

new RN 0.42.0

**Comment by DanielMSchmidt** [comment] 2017-03-08 07:33
This may be a duplicate of #3, I will have a look into it. Could be that this bug isn't fixed after all

**Comment by DanielMSchmidt** [comment] 2017-03-12 21:30
Hi @kasterlod , I just found some time to look into this issue and I could not reproduce the bug on the iOS simulator or on my android device. Would you be able to provide a little example project where I can see the bug sothat I can debug it?

**Comment by kasterlod** [comment] 2017-03-13 06:18
Hi!

Ok, so the problem was:
* Before RN upgrade (<0.42.0)
drawerPosition={Platform.OS == 'Android' ? DrawerLayoutAndroid.positions.Left: 'left'}

* after upgrade, the code line above causing the problem. Changing to below make it working again:
drawerPosition={'left'}

But now:
* the drawer is opening under toolbar.
* when drawer is opened there's seems to not every touch on mask is catching (to close drawer)

I'm using default code as below:

<DrawerLayout
                    drawerWidth={250}
                    drawerPosition={'left'}
                    renderNavigationView={() => navigationView}
                    ref={'DRAWER'}>
                    <Toolbar <...some code...> />
                    <Navigator <...some code...> />
</DrawerLayout>

On the iOS there's everything work great.
Thank's and greetings!

**Comment by DanielMSchmidt** [comment] 2017-03-17 08:15
Can you verify that this is still a problem with the latest version published today?

**Comment by kasterlod** [comment] 2017-03-20 12:16
Hi!

It seems like everything work now but still the toollbar is over the drawer.

greetings

**Comment by DanielMSchmidt** [comment] 2017-03-20 12:18
Okay, I will start looking into this topic the next couple of days 👍

**Comment by DanielMSchmidt** [comment] 2017-03-29 20:15
@kasterlod I debugged this problem, here is the comment about it: https://github.com/react-community/react-navigation/issues/709#issuecomment-290211241

**Comment by DanielMSchmidt** [comment] 2017-03-29 20:15
Closing this for now, as this seems to be a problem in react-navigation itself

**Closed as completed by DanielMSchmidt** 2017-03-29 20:15 UTC
Labels: bug
